<a href="https://colab.research.google.com/github/Tarikol-Islam/Linear-Regression-in-predicting/blob/main/Linear_Regression_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
from google.colab import files
uploaded = files.upload()

Saving homeprice.csv to homeprice.csv


In [5]:
df = pd.read_csv('homeprice.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       5.0   30  595000
4  4000       3.0    8  760000

In [7]:
import math
median_bedrooms = math.floor(df.bedrooms.median())

In [8]:
median_bedrooms

3

In [9]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    3.0
3    5.0
4    3.0
Name: bedrooms, dtype: float64

In [10]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       5.0   30  595000
4  4000       3.0    8  760000

In [11]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [12]:
df


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       5.0   30  595000
4  4000       3.0    8  760000

In [13]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
reg.coef_, reg.intercept_

(array([   138.55459057, -33456.52796335,  -1755.8217217 ]),
 313940.39893109363)

In [15]:
reg.predict([[3600,5,30]])

array([592779.63351785])

In [18]:
area = 4000
bedrooms = 6
age = 10
reg.predict([[area,bedrooms,age]])

array([649861.37621684])

In [22]:
arr = reg.predict([[int(input("Enter Area: ")),int(input("Enter Bedrooms: ")),int(input("Enter Age: "))]])

Enter Area: 2500
Enter Bedrooms: 4
Enter Age: 5


In [23]:
arr

array([517721.65489597])

In [24]:
*arr

SyntaxError: ignored

In [26]:
import sys

In [27]:
np.savetxt(sys.stdout, arr)

5.177216548959726351e+05
